<?php

return [
    'template_categories' => [
        ['key' => 'presentation', 'label' => 'Presentation', 'description' => 'Websites for companies, clinics, local services, and personal brands.'],
        ['key' => 'sales', 'label' => 'Sales', 'description' => 'Landing pages for offers, courses, campaigns, and premium services.'],
        ['key' => 'booking', 'label' => 'Bookings', 'description' => 'Websites for rentals, stays, appointments, and availability.'],
        ['key' => 'ecommerce', 'label' => 'Online store', 'description' => 'Templates for products, catalogs, carts, and orders.'],
        ['key' => 'custom-platform', 'label' => 'Custom platforms', 'description' => 'Dashboards, accounts, CRM, portals, and internal apps.'],
    ],
    'packages' => [
        ['id' => 1, 'key' => 'start', 'name' => 'Start', 'badge' => 'Simple', 'label' => 'For getting started', 'price' => 2500, 'description' => 'For a simple and clear website suitable for an early-stage business.', 'clientDescription' => 'Done-for-you website based on the selected template.', 'features' => ['Selected website template', 'Color and text adaptation', '4-5 main sections', 'Contact form', 'Mobile and desktop version', 'Basic Google setup']],
        ['id' => 2, 'key' => 'pro', 'name' => 'Pro', 'badge' => 'Recommended', 'label' => 'Most selected', 'price' => 4500, 'description' => 'For a business that needs a complete and more convincing website.', 'clientDescription' => 'Complete website with more sections and features.', 'features' => ['Everything included in Start', 'More personalized sections', 'Extra features', 'Clearer content structure', 'Speed optimization', 'Promotion preparation']],
        ['id' => 3, 'key' => 'premium', 'name' => 'Premium', 'badge' => 'Complete', 'label' => 'For premium image', 'price' => 7500, 'description' => 'For projects that need a premium image and a more advanced structure.', 'clientDescription' => 'A more complex website seriously adapted to the business.', 'features' => ['Everything included in Pro', 'More personalized design', 'Extra pages', 'Advanced features', 'Sales or request structure', 'Launch support']],
    ],
    'features' => [
        ['id' => 1, 'category' => 'Contact', 'name' => 'Contact form', 'plainName' => 'The client can send name, phone, email, and message.', 'price' => 300, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 2, 'category' => 'Contact', 'name' => 'Phone / email button', 'plainName' => 'The visitor can call or send an email quickly.', 'price' => 150, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 3, 'category' => 'Bookings', 'name' => 'Booking form', 'plainName' => 'The client can request a date, time, or period.', 'price' => 600, 'availableFor' => ['pro', 'premium']],
        ['id' => 4, 'category' => 'Content', 'name' => 'Photo / video gallery', 'plainName' => 'Show photos, work examples, rooms, products, or results.', 'price' => 400, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 5, 'category' => 'Content', 'name' => 'Services and pricing list', 'plainName' => 'Clearly show what you offer and how much it costs.', 'price' => 350, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 6, 'category' => 'Content', 'name' => 'Frequently asked questions', 'plainName' => 'Answer common client questions in advance.', 'price' => 250, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 7, 'category' => 'Trust', 'name' => 'Testimonials / reviews', 'plainName' => 'Show client opinions or result examples.', 'price' => 350, 'availableFor' => ['pro', 'premium']],
        ['id' => 8, 'category' => 'Location', 'name' => 'Google Maps', 'plainName' => 'The client can quickly see where to find you.', 'price' => 250, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 9, 'category' => 'Sales', 'name' => 'Product catalog', 'plainName' => 'Display products with image, price, and description.', 'price' => 900, 'availableFor' => ['pro', 'premium']],
        ['id' => 10, 'category' => 'Administration', 'name' => 'Client requests dashboard', 'plainName' => 'View received requests in a simple admin panel.', 'price' => 1200, 'availableFor' => ['pro', 'premium']],
        ['id' => 11, 'category' => 'Marketing', 'name' => 'Google Analytics', 'plainName' => 'See how many people visit the website and which pages they access.', 'price' => 300, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 12, 'category' => 'Advanced', 'name' => 'Romanian and English website', 'plainName' => 'Website with two languages: Romanian and English.', 'price' => 1500, 'availableFor' => ['pro', 'premium']],
    ],
    'templates' => [
        ['id' => 1, 'slug' => 'business-essence', 'categoryKey' => 'presentation', 'category' => 'Presentation', 'name' => 'Business Essence', 'shortTitle' => 'Website for local business', 'description' => 'For local businesses, clinics, consulting, premium services, or personal brands.', 'basePrice' => 2500, 'buildPriceFrom' => 2500, 'deliveryTime' => '5-7 days', 'idealFor' => ['Local businesses', 'Clinics', 'Consulting'], 'pages' => ['Home', 'About', 'Services', 'Contact']],
        ['id' => 2, 'slug' => 'premium-studio', 'categoryKey' => 'presentation', 'category' => 'Beauty & Salon', 'name' => 'Premium Studio', 'shortTitle' => 'Website for premium studio', 'description' => 'For beauty, photography, wellness, interior design, or creative services.', 'basePrice' => 3500, 'buildPriceFrom' => 3500, 'deliveryTime' => '7-10 days', 'idealFor' => ['Beauty', 'Photography', 'Wellness'], 'pages' => ['Home', 'Portfolio', 'Services', 'Contact']],
        ['id' => 3, 'slug' => 'launch-page', 'categoryKey' => 'sales', 'category' => 'Launch', 'name' => 'Launch Page', 'shortTitle' => 'Landing page', 'description' => 'For promoting a product, service, course, or limited offer.', 'basePrice' => 2500, 'buildPriceFrom' => 2500, 'deliveryTime' => '5-7 days', 'idealFor' => ['Campaigns', 'Courses', 'Services'], 'pages' => ['Landing page']],
        ['id' => 4, 'slug' => 'conversion-flow', 'categoryKey' => 'sales', 'category' => 'Campaign', 'name' => 'Conversion Flow', 'shortTitle' => 'Conversion page', 'description' => 'Sales page with benefits, testimonials, offer, and clear buttons.', 'basePrice' => 3500, 'buildPriceFrom' => 3500, 'deliveryTime' => '7-10 days', 'idealFor' => ['Premium services', 'Courses', 'Campaigns'], 'pages' => ['Extended landing page']],
        ['id' => 5, 'slug' => 'rental-flow', 'categoryKey' => 'booking', 'category' => 'Bookings', 'name' => 'Rental Flow', 'shortTitle' => 'Booking website', 'description' => 'For services where the client requests availability, period, or appointment.', 'basePrice' => 4500, 'buildPriceFrom' => 4500, 'deliveryTime' => '7-14 days', 'idealFor' => ['Bookings', 'Appointments', 'Availability'], 'pages' => ['Home', 'Rates', 'Booking', 'Contact']],
        ['id' => 6, 'slug' => 'tourism-stay', 'categoryKey' => 'booking', 'category' => 'Tourism', 'name' => 'Tourism Stay', 'shortTitle' => 'Accommodation website', 'description' => 'For guesthouses, apartments, cabins, or tourism experiences.', 'basePrice' => 4500, 'buildPriceFrom' => 4500, 'deliveryTime' => '7-14 days', 'idealFor' => ['Stays', 'Guesthouses', 'Cabins'], 'pages' => ['Home', 'Rooms', 'Gallery', 'Contact']],
        ['id' => 7, 'slug' => 'simple-shop', 'categoryKey' => 'ecommerce', 'category' => 'Online store', 'name' => 'Simple Shop', 'shortTitle' => 'Simple online store', 'description' => 'For businesses that want to show products and receive requests or orders.', 'basePrice' => 7500, 'buildPriceFrom' => 7500, 'deliveryTime' => '14-21 days', 'idealFor' => ['Local products', 'Handmade', 'Online catalog'], 'pages' => ['Home', 'Products', 'Categories', 'Contact']],
        ['id' => 8, 'slug' => 'premium-store', 'categoryKey' => 'ecommerce', 'category' => 'E-commerce', 'name' => 'Premium Store', 'shortTitle' => 'Premium online store', 'description' => 'Complete structure for products, variants, cart, and checkout.', 'basePrice' => 9500, 'buildPriceFrom' => 9500, 'deliveryTime' => '21+ days', 'idealFor' => ['Online stores', 'Brands', 'Premium products'], 'pages' => ['Shop', 'Product', 'Cart', 'Checkout']],
        ['id' => 9, 'slug' => 'client-portal', 'categoryKey' => 'custom-platform', 'category' => 'Custom platform', 'name' => 'Client Portal', 'shortTitle' => 'Client portal', 'description' => 'Platform with authentication, client accounts, dashboard, and custom features.', 'basePrice' => 12000, 'buildPriceFrom' => 12000, 'deliveryTime' => '21+ days', 'idealFor' => ['Dashboards', 'CRMs', 'Internal platforms'], 'pages' => ['Login', 'Dashboard', 'Administration']],
    ],
];
