<?php

return [
    'creare-site-de-prezentare-brasov' => [
        'title' => 'Creare site de prezentare Brașov',
        'description' => 'SiteGo creează site-uri de prezentare pentru afaceri locale din Brașov, cu structură clară, design modern și formular de contact.',
        'eyebrow' => 'Web design local în Brașov',
        'h1' => 'Creare site de prezentare în Brașov pentru afaceri locale',
        'intro' => 'Un site de prezentare bun explică rapid cine ești, ce servicii oferi și cum te poate contacta clientul. SiteGo te ajută să ai o prezență online clară, modernă și ușor de folosit.',
        'service_type' => 'Creare site de prezentare',
        'includes' => ['Structură clară pentru servicii', 'Design modern și responsive', 'Formular de contact', 'Buton WhatsApp', 'SEO de bază', 'Configurare Analytics și Search Console'],
        'for_who' => 'Este potrivit pentru saloane, cabinete, freelanceri, firme de servicii, restaurante, fotografi și afaceri locale care vor să fie găsite mai ușor online.',
        'process' => 'Începem cu structura și mesajul principal, alegem secțiunile potrivite, construim pagina, testăm varianta de mobil și publicăm site-ul.',
        'benefits' => [
            ['title' => 'Claritate', 'text' => 'Clientul înțelege rapid ce oferi și de ce să te contacteze.'],
            ['title' => 'Încredere', 'text' => 'Un site modern transmite profesionalism și reduce dependența de social media.'],
            ['title' => 'Contact rapid', 'text' => 'Butonul de WhatsApp și formularul scurtează drumul dintre vizitator și cerere.'],
        ],
    ],
    'web-design-brasov' => [
        'title' => 'Web design Brașov',
        'description' => 'Servicii de web design în Brașov pentru afaceri locale care vor un site modern, clar și adaptat pentru mobil.',
        'eyebrow' => 'Web design Brașov',
        'h1' => 'Web design în Brașov pentru site-uri moderne și clare',
        'intro' => 'Designul unui site nu înseamnă doar culori frumoase. Înseamnă structură, încredere, butoane clare și o experiență bună pe telefon.',
        'service_type' => 'Web design',
        'includes' => ['Design adaptat brandului', 'Secțiuni pentru servicii', 'CTA vizibile', 'Optimizare pentru mobil', 'Pagină de contact', 'Integrare cu Google Business'],
        'for_who' => 'Pentru afaceri din Brașov care au deja un site vechi sau pornesc de la zero și vor o imagine mai profesionistă online.',
        'process' => 'Stabilim obiectivul site-ului, refacem structura, pregătim textele esențiale și construim un design aerisit, ușor de parcurs.',
        'benefits' => [
            ['title' => 'Mai multă încredere', 'text' => 'Un design curat face afacerea să pară mai serioasă.'],
            ['title' => 'Mai ușor de citit', 'text' => 'Textele și serviciile sunt organizate pentru vizitatori reali.'],
            ['title' => 'Mai bun pe mobil', 'text' => 'Majoritatea clienților intră de pe telefon, deci pagina trebuie să se miște natural.'],
        ],
    ],
    'realizare-website-brasov' => [
        'title' => 'Realizare website Brașov',
        'description' => 'Realizare website pentru afaceri din Brașov: site de prezentare, landing page, configurare contact, SEO de bază și Analytics.',
        'eyebrow' => 'Realizare website',
        'h1' => 'Realizare website în Brașov, de la idee la publicare',
        'intro' => 'SiteGo te ajută să transformi informațiile despre afacerea ta într-un website simplu, clar și pregătit pentru promovare.',
        'service_type' => 'Realizare website',
        'includes' => ['Structură pagini', 'Texte de bază', 'Design responsive', 'Formular lead', 'Configurări Google', 'Publicare pe domeniu'],
        'for_who' => 'Pentru antreprenori care nu vor să piardă timp cu partea tehnică și vor o variantă clară, completă și ușor de administrat.',
        'process' => 'Alegem modelul potrivit, stabilim secțiunile, pregătim conținutul, construim website-ul și îl testăm înainte de publicare.',
        'benefits' => [
            ['title' => 'Proces simplu', 'text' => 'Nu trebuie să știi partea tehnică. Primești pașii clari.'],
            ['title' => 'Imagine coerentă', 'text' => 'Site-ul este construit în jurul serviciilor și obiectivului tău.'],
            ['title' => 'Pregătit pentru promovare', 'text' => 'Poți folosi site-ul în Google Business, social media și campanii.'],
        ],
    ],
    'realizare-site-brasov' => [
        'title' => 'Realizare site Brașov',
        'description' => 'Realizare site în Brașov pentru firme locale, saloane, servicii, cabinete și afaceri care vor o prezență online profesionistă.',
        'eyebrow' => 'Realizare site Brașov',
        'h1' => 'Realizare site în Brașov pentru afacerea ta',
        'intro' => 'Un site realizat corect trebuie să fie clar, rapid, adaptat pentru mobil și ușor de folosit de clienți. SiteGo te ajută să pornești de la o structură potrivită.',
        'service_type' => 'Realizare site',
        'includes' => ['Structură pentru servicii', 'Design responsive', 'Texte adaptate', 'Formular contact', 'WhatsApp', 'SEO local de bază'],
        'for_who' => 'Pentru afaceri din Brașov care au nevoie de un site nou sau de o variantă mai clară decât pagina de Facebook.',
        'process' => 'Discutăm obiectivul, alegem structura, pregătim textele, construim site-ul, testăm varianta de mobil și îl publicăm.',
        'benefits' => [
            ['title' => 'Prezență proprie', 'text' => 'Nu depinzi doar de social media sau recomandări.'],
            ['title' => 'Mai multă claritate', 'text' => 'Clientul vede rapid serviciile, programul și modalitățile de contact.'],
            ['title' => 'Pregătit pentru Google', 'text' => 'Pagina are structură și elemente de bază pentru indexare.'],
        ],
    ],
    'creare-site-brasov' => [
        'title' => 'Creare site Brașov',
        'description' => 'Creare site în Brașov pentru afaceri mici și locale: site de prezentare, pagină de servicii, formular și structură pentru Google.',
        'eyebrow' => 'Creare site Brașov',
        'h1' => 'Creare site în Brașov pentru afaceri locale',
        'intro' => 'Dacă ai o afacere locală, site-ul trebuie să explice rapid ce oferi, pentru cine este serviciul și cum poate clientul să te contacteze.',
        'service_type' => 'Creare site',
        'includes' => ['Pagină principală clară', 'Secțiuni pentru servicii', 'Contact rapid', 'Variantă mobilă', 'SEO basic', 'Pregătire pentru lansare'],
        'for_who' => 'Pentru firme locale, saloane, fotografi, freelanceri, cabinete, restaurante și servicii care vor o imagine mai profesionistă.',
        'process' => 'Pornim de la obiectiv, alegem structura potrivită, adaptăm textele și construim site-ul final.',
        'benefits' => [
            ['title' => 'Start rapid', 'text' => 'Poți începe cu o structură simplă și clară.'],
            ['title' => 'Cost controlat', 'text' => 'Nu adăugăm funcții inutile din prima etapă.'],
            ['title' => 'Extindere ușoară', 'text' => 'Site-ul poate crește ulterior cu pagini, blog, rezervări sau catalog.'],
        ],
    ],
    'constructie-site-brasov' => [
        'title' => 'Construcție site Brașov',
        'description' => 'Construcție site în Brașov: structură, design, dezvoltare, formular, publicare pe domeniu și optimizare de bază.',
        'eyebrow' => 'Construcție site',
        'h1' => 'Construcție site în Brașov, de la structură la lansare',
        'intro' => 'Construcția unui site nu înseamnă doar design. Înseamnă pagini clare, funcții potrivite, formulare, testare și publicare corectă.',
        'service_type' => 'Construcție site',
        'includes' => ['Structură site', 'Design responsive', 'Dezvoltare tehnică', 'Formular de contact', 'Testare mobil', 'Publicare pe domeniu'],
        'for_who' => 'Pentru antreprenori care vor un site construit corect, cu pași clari și fără discuții tehnice complicate.',
        'process' => 'Stabilim ce trebuie să facă site-ul, construim secțiunile, testăm formularele și pregătim publicarea.',
        'benefits' => [
            ['title' => 'Mai puține blocaje', 'text' => 'Ai un proces clar, nu o listă confuză de termeni tehnici.'],
            ['title' => 'Funcții potrivite', 'text' => 'Adăugăm doar ce ajută afacerea acum.'],
            ['title' => 'Site pregătit de lansare', 'text' => 'Verificăm aspectul, contactul și funcționarea înainte de publicare.'],
        ],
    ],
    'firma-web-design-brasov' => [
        'title' => 'Firmă web design Brașov',
        'description' => 'Firmă de web design în Brașov pentru afaceri locale care au nevoie de site de prezentare, landing page sau soluții digitale.',
        'eyebrow' => 'Firmă web design Brașov',
        'h1' => 'Firmă de web design în Brașov pentru afaceri locale',
        'intro' => 'SiteGo lucrează cu afaceri care vor o prezență online clară: site-uri de prezentare, pagini de campanie, formulare și soluții digitale adaptate.',
        'service_type' => 'Firmă web design',
        'includes' => ['Consultanță inițială', 'Structură site', 'Design modern', 'Dezvoltare', 'Contact rapid', 'Lansare asistată'],
        'for_who' => 'Pentru firme care vor să lucreze organizat, să aibă o direcție clară și să primească un site ușor de folosit.',
        'process' => 'Începem cu nevoia reală a businessului, alegem direcția potrivită și construim site-ul în pași clari.',
        'benefits' => [
            ['title' => 'Colaborare clară', 'text' => 'Știi ce primești și ce urmează.'],
            ['title' => 'Orientare pe business', 'text' => 'Site-ul este gândit pentru contact, încredere și conversii.'],
            ['title' => 'Suport după lansare', 'text' => 'Putem continua cu mentenanță, ajustări și extinderi.'],
        ],
    ],
    'agentie-web-design-brasov' => [
        'title' => 'Agenție web design Brașov',
        'description' => 'Agenție web design Brașov pentru site-uri moderne, responsive și orientate spre cereri reale din partea clienților.',
        'eyebrow' => 'Agenție web design',
        'h1' => 'Agenție web design Brașov pentru site-uri moderne',
        'intro' => 'SiteGo oferă o abordare practică pentru afaceri locale: structură clară, design modern, funcții utile și pași simpli până la lansare.',
        'service_type' => 'Agenție web design',
        'includes' => ['Strategie de pagină', 'Design UI', 'Dezvoltare web', 'SEO basic', 'Analytics la cerere', 'Suport lansare'],
        'for_who' => 'Pentru afaceri care vor un partener digital, nu doar o pagină făcută rapid și abandonată după lansare.',
        'process' => 'Analizăm obiectivul, alegem structura, construim site-ul și îl pregătim pentru folosire reală.',
        'benefits' => [
            ['title' => 'Imagine profesională', 'text' => 'Site-ul transmite mai multă încredere.'],
            ['title' => 'Experiență bună pe mobil', 'text' => 'Structura este gândită pentru utilizatori care intră de pe telefon.'],
            ['title' => 'Direcție clară', 'text' => 'Ai pagini, secțiuni și CTA-uri gândite cu scop.'],
        ],
    ],
    'landing-page-afaceri' => [
        'title' => 'Landing page pentru afaceri',
        'description' => 'Landing page pentru promovarea unui serviciu, produs sau campanii locale. Pagină clară, cu CTA și formular de contact.',
        'eyebrow' => 'Landing page',
        'h1' => 'Landing page pentru afaceri care vor cereri mai clare',
        'intro' => 'O pagină de tip landing page se concentrează pe un singur obiectiv: să explice oferta și să transforme vizitatorul în lead.',
        'service_type' => 'Landing page',
        'includes' => ['Hero cu ofertă clară', 'Beneficii', 'Secțiune servicii', 'Întrebări frecvente', 'Formular contact', 'CTA repetat'],
        'for_who' => 'Potrivit pentru campanii, lansări, servicii sezoniere, promoții sau afaceri care vor să trimită trafic din TikTok, Facebook sau Google.',
        'process' => 'Construim pagina în jurul unei oferte clare, cu secțiuni scurte, beneficii vizibile și butoane de contact așezate strategic.',
        'benefits' => [
            ['title' => 'Focus pe conversie', 'text' => 'Pagina are un singur scop și nu risipește atenția vizitatorului.'],
            ['title' => 'Ideal pentru reclame', 'text' => 'Poți trimite trafic din TikTok, Facebook, Instagram sau Google.'],
            ['title' => 'Rapid de lansat', 'text' => 'Se poate construi mai repede decât un website complet.'],
        ],
    ],
    'site-salon-beauty' => [
        'title' => 'Site pentru salon beauty',
        'description' => 'Site de prezentare pentru salon beauty, coafor, makeup artist, stilist sau servicii de înfrumusețare.',
        'eyebrow' => 'Site pentru beauty',
        'h1' => 'Site pentru salon beauty, coafor sau servicii de înfrumusețare',
        'intro' => 'Un salon are nevoie de poze bune, servicii clare, prețuri orientative și un mod rapid prin care clientele pot cere programare.',
        'service_type' => 'Site pentru salon beauty',
        'includes' => ['Servicii beauty', 'Galerie foto', 'Buton programare', 'WhatsApp', 'Recenzii', 'Hartă și program'],
        'for_who' => 'Pentru saloane, coafeze, makeup artiști, stiliste, cosmeticiene, nail artists și afaceri din zona de beauty.',
        'process' => 'Punem accent pe imagine, servicii, programări și încredere. Pagina trebuie să arate bine pe telefon și să ducă rapid spre contact.',
        'benefits' => [
            ['title' => 'Programări mai simple', 'text' => 'Clientele pot ajunge rapid la WhatsApp sau formular.'],
            ['title' => 'Servicii clare', 'text' => 'Fiecare serviciu este prezentat pe scurt, fără aglomerație.'],
            ['title' => 'Imagine premium', 'text' => 'Designul ajută salonul să pară îngrijit și profesionist.'],
        ],
    ],
    'cat-costa-un-site-de-prezentare-2026' => [
        'title' => 'Cât costă un site de prezentare în 2026',
        'description' => 'Explicație clară despre cât poate costa un site de prezentare în 2026 și ce influențează prețul.',
        'eyebrow' => 'Ghid de preț',
        'h1' => 'Cât costă un site de prezentare în 2026?',
        'intro' => 'Prețul unui site depinde de numărul de pagini, nivelul de personalizare, texte, poze, formulare, SEO și configurările tehnice necesare.',
        'service_type' => 'Consultanță website',
        'includes' => ['Estimare preț', 'Explicații clare', 'Ce include un site', 'Ce costă extra', 'Recomandări pentru început', 'Link către configurator'],
        'for_who' => 'Pentru antreprenori care vor să înțeleagă realist ce buget trebuie să pregătească pentru un site de prezentare.',
        'process' => 'Cel mai simplu este să pornești cu un site clar, nu cu multe funcții inutile. Ulterior poți adăuga pagini, blog, portofoliu sau funcționalități suplimentare.',
        'benefits' => [
            ['title' => 'Buget mai clar', 'text' => 'Înțelegi ce influențează costul înainte să ceri ofertă.'],
            ['title' => 'Fără funcții inutile', 'text' => 'Poți începe cu exact ce ai nevoie acum.'],
            ['title' => 'Configurator util', 'text' => 'Poți estima mai ușor varianta potrivită pentru afacerea ta.'],
        ],
    ],
];
