<?php

return [
    'creare-site-web' => [
        'title' => 'Creare site web pentru afaceri | SiteGo',
        'description' => 'Creare site web pentru afaceri din România: site-uri de prezentare, magazine online, rezervări și dezvoltare web personalizată, responsive și pregătită pentru Google.',
        'eyebrow' => 'Creare site web · România & online',
        'h1' => 'Creare site web pentru afaceri care vor să fie găsite, înțelese și contactate',
        'intro' => 'SiteGo construiește site-uri și aplicații web pentru afaceri din toată România, cu colaborare complet online și proiecte care pot fi livrate și pentru clienți internaționali. Pornim de la obiectivul afacerii, nu de la un șablon generic.',
        'service_type' => 'Creare site web și dezvoltare web',
        'area_served' => 'România',
        'includes' => [
            'Structură clară, adaptată serviciilor sau produselor tale',
            'Design responsive pentru telefon, tabletă și desktop',
            'Formulare, WhatsApp, rezervări, catalog sau fluxuri custom',
            'SEO tehnic de bază: titluri, descrieri, canonical, sitemap și date structurate',
            'Configurare Search Console și Analytics la lansare',
            'Posibilitate de administrare și extindere ulterioară',
        ],
        'for_who' => 'Pentru antreprenori, PFA-uri, firme de servicii, cabinete, saloane, închirieri, magazine, proiecte B2B și afaceri care au nevoie de o prezență online clară sau de funcționalități dezvoltate la comandă.',
        'process' => 'Clarificăm obiectivul, stabilim structura și funcționalitățile, construim interfața, testăm pe mobil și desktop, apoi publicăm și verificăm indexarea și formularele.',
        'benefits' => [
            ['title' => 'Site construit pentru business', 'text' => 'Arhitectura pornește de la ce trebuie să facă utilizatorul: să înțeleagă, să compare, să rezerve, să comande sau să te contacteze.'],
            ['title' => 'Colaborare online', 'text' => 'Putem lucra complet remote, indiferent de oraș, iar proiectele nu sunt limitate la Brașov.'],
            ['title' => 'Bază tehnică sănătoasă', 'text' => 'Livrarea include o structură indexabilă, responsive și pregătită pentru dezvoltări ulterioare.'],
        ],
        'proof' => [
            ['title' => 'RentRide', 'href' => '/portofoliu/rentride', 'text' => 'Platformă live pentru închirieri de scutere și biciclete electrice.'],
            ['title' => 'Access Happiness', 'href' => '/portofoliu/access-bars-beatris', 'text' => 'Site de prezentare pentru servicii și programări.'],
            ['title' => 'Happiness Atelier', 'href' => '/portofoliu/happiness-atelier', 'text' => 'Catalog și rezervări pentru închirierea rochiilor.'],
        ],
        'faqs' => [
            ['question' => 'Lucrați doar cu firme din Brașov?', 'answer' => 'Nu. Colaborarea poate fi complet online, iar SiteGo lucrează cu afaceri din toată România. Pentru proiecte internaționale putem lucra în limba engleză și adapta site-ul pieței țintă.'],
            ['question' => 'Site-ul va putea apărea în Google?', 'answer' => 'Da, construim baza tehnică necesară indexării. Poziția în rezultate depinde și de concurență, conținut, reputație, linkuri și autoritatea domeniului.'],
            ['question' => 'Pot începe cu o variantă simplă și să adaug funcții ulterior?', 'answer' => 'Da. Putem porni cu funcțiile esențiale și extinde ulterior cu rezervări, catalog, plăți, conturi de client, automatizări sau administrare.'],
            ['question' => 'Puteți lucra pe un site existent?', 'answer' => 'Da. Putem reface structura, designul, performanța, SEO-ul tehnic sau anumite funcționalități ale unui proiect existent.'],
        ],
        'related' => [
            ['title' => 'Landing page', 'href' => '/landing-page'],
            ['title' => 'Mentenanță și dezvoltări', 'href' => '/mentenanta-site'],
            ['title' => 'Portofoliu', 'href' => '/portofoliu'],
        ],
        'en' => [
            'title' => 'Website development for businesses | SiteGo',
            'description' => 'Website development for businesses: presentation websites, online stores, booking systems and custom web development, responsive and search-friendly.',
            'eyebrow' => 'Website development · remote collaboration',
            'h1' => 'Websites for businesses that want to be found, understood and contacted',
            'intro' => 'SiteGo builds websites and custom web solutions for businesses in Romania and works remotely with international clients. We start with the business goal, not with a generic template.',
            'service_type' => 'Website design and web development',
            'area_served' => 'Romania and remote international projects',
            'includes' => [
                'Clear structure adapted to your services or products',
                'Responsive design for mobile, tablet and desktop',
                'Forms, WhatsApp, bookings, catalogues or custom flows',
                'Technical SEO foundation: titles, descriptions, canonical, sitemap and structured data',
                'Search Console and Analytics setup at launch',
                'Administration and future extensions when needed',
            ],
            'for_who' => 'For entrepreneurs, service businesses, clinics, salons, rentals, stores, B2B projects and companies that need a clear online presence or custom functionality.',
            'process' => 'We clarify the goal, define the structure and functionality, build the interface, test it across devices, then launch and verify indexing and forms.',
            'benefits' => [
                ['title' => 'Built around the business', 'text' => 'The structure is designed around what visitors need to do: understand, compare, book, order or contact you.'],
                ['title' => 'Remote collaboration', 'text' => 'The project can be handled online from start to launch, regardless of location.'],
                ['title' => 'Healthy technical foundation', 'text' => 'The website is delivered responsive, indexable and ready for future development.'],
            ],
            'faqs' => [
                ['question' => 'Do you work with international clients?', 'answer' => 'Yes. We can collaborate remotely in English and adapt the website structure and copy to the target market.'],
                ['question' => 'Can the website appear in Google?', 'answer' => 'Yes. We build the technical foundation for crawling and indexing, while rankings also depend on competition, content, authority and external signals.'],
            ],
        ],
    ],

    'mentenanta-site' => [
        'title' => 'Mentenanță site și dezvoltări ulterioare | SiteGo',
        'description' => 'Mentenanță website, corecții, actualizări, optimizări și dezvoltări ulterioare pentru site-uri și aplicații web.',
        'eyebrow' => 'Mentenanță & evoluție',
        'h1' => 'Mentenanță site pentru proiecte care trebuie să rămână stabile și să evolueze',
        'intro' => 'După lansare pot apărea ajustări, conținut nou, funcții suplimentare sau probleme tehnice. Putem lucra punctual sau recurent, în funcție de proiect.',
        'service_type' => 'Mentenanță website și suport tehnic',
        'area_served' => 'Remote',
        'includes' => [
            'Corecții și verificări tehnice',
            'Actualizări de conținut și mici ajustări',
            'Funcționalități noi',
            'Optimizări de performanță și UX',
            'Verificări SEO tehnice',
            'Suport și prioritizare pe bază de abonament, unde este potrivit',
        ],
        'for_who' => 'Pentru site-uri și aplicații care au nevoie de intervenții periodice, dezvoltare treptată sau o persoană tehnică ce poate prelua modificările organizat.',
        'process' => 'Evaluăm starea proiectului și modul în care este construit, stabilim tipurile de intervenții și lucrăm punctual sau pe o listă prioritară recurentă.',
        'benefits' => [
            ['title' => 'Stabilitate', 'text' => 'Problemele sunt urmărite și rezolvate înainte să afecteze utilizatorii pe termen lung.'],
            ['title' => 'Evoluție controlată', 'text' => 'Funcțiile și conținutul pot fi adăugate treptat, fără schimbări haotice.'],
            ['title' => 'Un singur context tehnic', 'text' => 'Păstrăm istoricul modificărilor și prioritățile într-un proces mai clar.'],
        ],
        'proof' => [
            ['title' => 'Portofoliu SiteGo', 'href' => '/portofoliu', 'text' => 'Vezi proiecte care au continuat să evolueze după lansare.'],
        ],
        'faqs' => [
            ['question' => 'Oferiți doar abonamente?', 'answer' => 'Nu. Putem lucra și punctual. Abonamentul are sens doar pentru proiectele care au nevoie de intervenții recurente.'],
            ['question' => 'Puteți face mentenanță pe un site construit de altcineva?', 'answer' => 'Da, după o verificare tehnică inițială.'],
        ],
        'related' => [
            ['title' => 'Creare site web', 'href' => '/creare-site-web'],
            ['title' => 'Portofoliu', 'href' => '/portofoliu'],
            ['title' => 'Contact', 'href' => '/contact?topic=abonament'],
        ],
        'en' => [
            'title' => 'Website maintenance and ongoing development | SiteGo',
            'description' => 'Website maintenance, fixes, updates, optimization and ongoing development for websites and web applications.',
            'eyebrow' => 'Maintenance & growth',
            'h1' => 'Website maintenance for projects that need to stay stable and keep evolving',
            'service_type' => 'Website maintenance and technical support',
        ],
    ],

    'landing-page' => [
        'title' => 'Landing page pentru servicii, produse și campanii | SiteGo',
        'description' => 'Landing page pentru promovarea unui serviciu, produs sau campanii: mesaj clar, CTA, formular, tracking și structură orientată spre conversii.',
        'eyebrow' => 'Landing page',
        'h1' => 'Landing page construit pentru o ofertă clară și o singură acțiune importantă',
        'intro' => 'Un landing page bun are un obiectiv clar. Eliminăm distragerile, explicăm oferta, răspundem obiecțiilor principale și repetăm acțiunea pe care vrei să o facă vizitatorul.',
        'service_type' => 'Landing page',
        'area_served' => 'Remote',
        'includes' => [
            'Hero cu ofertă și CTA clar',
            'Beneficii și diferențiatori',
            'Dovezi, proiecte sau testimoniale',
            'FAQ și răspunsuri la obiecții',
            'Formular de lead sau contact rapid',
            'Tracking pentru campanii și conversii, la nevoie',
        ],
        'for_who' => 'Pentru reclame Google, Meta sau TikTok, lansări, servicii premium, evenimente, promoții și situații în care o pagină generală ar dispersa atenția.',
        'process' => 'Pornim de la ofertă și public, stabilim mesajul principal și secțiunile necesare, apoi construim pagina și traseul de conversie.',
        'benefits' => [
            ['title' => 'Un singur obiectiv', 'text' => 'Pagina conduce utilizatorul către o acțiune clară.'],
            ['title' => 'Potrivit pentru reclame', 'text' => 'Mesajul poate fi aliniat exact cu anunțul și publicul campaniei.'],
            ['title' => 'Ușor de măsurat', 'text' => 'Putem urmări trimiteri de formulare și alte acțiuni relevante.'],
        ],
        'proof' => [
            ['title' => 'Modele de site', 'href' => '/modele-site', 'text' => 'Vezi exemple de structură și direcții vizuale.'],
            ['title' => 'Portofoliu', 'href' => '/portofoliu', 'text' => 'Vezi proiecte publicate.'],
        ],
        'faqs' => [
            ['question' => 'Landing page sau site complet?', 'answer' => 'Landing page-ul este potrivit când ai un singur obiectiv sau o campanie. Un site complet este mai bun când trebuie să prezinți mai multe servicii și informații despre brand.'],
            ['question' => 'Pot folosi landing page-ul pentru Google Ads?', 'answer' => 'Da. Structura poate fi adaptată mesajului și conversiei urmărite în campanie.'],
        ],
        'related' => [
            ['title' => 'Creare site web', 'href' => '/creare-site-web'],
            ['title' => 'Portofoliu', 'href' => '/portofoliu'],
            ['title' => 'Contact', 'href' => '/contact'],
        ],
        'en' => [
            'title' => 'Landing page for services, products and campaigns | SiteGo',
            'description' => 'Landing pages for services, products and campaigns with a clear message, CTA, forms, tracking and conversion-focused structure.',
            'eyebrow' => 'Landing page',
            'h1' => 'A landing page built around one clear offer and one important action',
            'service_type' => 'Landing page',
        ],
    ],

    'site-pentru-salon' => [
        'title' => 'Site pentru salon beauty și programări | SiteGo',
        'description' => 'Site pentru salon beauty, coafor, makeup, nails sau wellness: servicii, galerie, programări, prețuri și contact rapid de pe telefon.',
        'eyebrow' => 'Site pentru salon',
        'h1' => 'Site pentru salon beauty construit pentru imagine, servicii și programări',
        'intro' => 'În beauty, site-ul trebuie să arate bine, dar și să fie practic. Clienta trebuie să poată vedea serviciile, lucrările, locația și să ajungă rapid la programare.',
        'service_type' => 'Website pentru salon beauty',
        'area_served' => 'România',
        'includes' => [
            'Servicii și informații despre proceduri',
            'Galerie foto cu lucrări reale',
            'Prețuri sau intervale orientative, dacă dorești',
            'Buton programare / WhatsApp',
            'Program, hartă și date de contact',
            'Design premium, responsive',
        ],
        'for_who' => 'Pentru saloane, hair stylists, nail artists, makeup artists, cosmeticieni, lash artists, spa și servicii de wellness din orice oraș.',
        'process' => 'Alegem stilul vizual potrivit brandului, organizăm serviciile și galeria, stabilim traseul către programare și optimizăm experiența pe mobil.',
        'benefits' => [
            ['title' => 'Imagine coerentă', 'text' => 'Fotografiile și serviciile sunt prezentate într-un design adaptat brandului.'],
            ['title' => 'Programări rapide', 'text' => 'Butoanele importante rămân ușor de găsit pe mobil.'],
            ['title' => 'Mai multă încredere', 'text' => 'Clienta găsește într-un singur loc servicii, lucrări și informații practice.'],
        ],
        'proof' => [
            ['title' => 'Modele SiteGo', 'href' => '/modele-site', 'text' => 'Vezi exemple vizuale pentru servicii beauty și business local.'],
            ['title' => 'Contact', 'href' => '/contact', 'text' => 'Spune-ne ce servicii și tip de programare folosești.'],
        ],
        'faqs' => [
            ['question' => 'Pot păstra programările pe WhatsApp?', 'answer' => 'Da. Site-ul poate trimite direct către WhatsApp sau poate avea un formular ori calendar separat.'],
            ['question' => 'Pot adăuga ulterior magazin pentru produse?', 'answer' => 'Da. Se poate extinde cu un catalog sau magazin pentru produse cosmetice și alte articole.'],
        ],
        'related' => [
            ['title' => 'Creare site web', 'href' => '/creare-site-web'],
            ['title' => 'Modele de site', 'href' => '/modele-site'],
            ['title' => 'Portofoliu', 'href' => '/portofoliu'],
        ],
        'en' => [
            'title' => 'Beauty salon website and bookings | SiteGo',
            'description' => 'Website for beauty salons, hair, makeup, nails or wellness with services, gallery, bookings and fast mobile contact.',
            'eyebrow' => 'Beauty salon website',
            'h1' => 'Beauty salon website built for image, services and bookings',
            'service_type' => 'Beauty salon website',
        ],
    ],

    'web-design-brasov' => [
        'title' => 'Web design Brașov | SiteGo',
        'description' => 'Web design în Brașov pentru firme și antreprenori: site-uri rapide, responsive, clare și pregătite pentru Google, contact și conversii.',
        'eyebrow' => 'Serviciu local · Brașov',
        'h1' => 'Web design în Brașov pentru afaceri care vor un site profesionist',
        'intro' => 'SiteGo este disponibil local în Brașov, dar colaborarea nu este limitată geografic. Această pagină este dedicată firmelor care caută explicit un partener de web design în Brașov.',
        'service_type' => 'Web design Brașov',
        'area_served' => 'Brașov',
        'includes' => [
            'Site-uri de prezentare și landing pages',
            'Magazine și cataloage online',
            'Rezervări și programări',
            'Dezvoltare web personalizată',
            'SEO tehnic și configurare Search Console',
            'Colaborare locală sau complet online',
        ],
        'for_who' => 'Pentru firme, PFA-uri și antreprenori din Brașov care vor un site nou, un redesign sau o soluție web personalizată.',
        'process' => 'Putem discuta online sau local, definim obiectivul și structura proiectului, dezvoltăm și testăm, apoi publicăm și verificăm partea tehnică.',
        'benefits' => [
            ['title' => 'Partener local', 'text' => 'Poți lucra cu un developer din Brașov fără să limitezi proiectul la o soluție locală sau simplă.'],
            ['title' => 'Proiecte reale', 'text' => 'În portofoliu există platforme și site-uri publicate pentru servicii, închirieri și rezervări.'],
            ['title' => 'Dezvoltare custom', 'text' => 'Putem merge dincolo de un site de prezentare atunci când proiectul are logică proprie.'],
        ],
        'proof' => [
            ['title' => 'RentRide', 'href' => '/portofoliu/rentride', 'text' => 'Platformă live de închirieri.'],
            ['title' => 'Access Happiness', 'href' => '/portofoliu/access-bars-beatris', 'text' => 'Site de servicii și programări.'],
            ['title' => 'Happiness Atelier', 'href' => '/portofoliu/happiness-atelier', 'text' => 'Catalog și rezervări pentru rochii.'],
        ],
        'faqs' => [
            ['question' => 'Lucrați doar în Brașov?', 'answer' => 'Nu. Brașov este baza locală, dar colaborarea poate fi complet online cu clienți din toată România și proiecte internaționale.'],
            ['question' => 'Putem avea o întâlnire înainte de ofertă?', 'answer' => 'Da. Putem discuta online, iar pentru proiectele locale putem stabili și o întâlnire atunci când este utilă.'],
        ],
        'related' => [
            ['title' => 'Creare site web', 'href' => '/creare-site-web'],
            ['title' => 'Mentenanță site', 'href' => '/mentenanta-site'],
            ['title' => 'Portofoliu', 'href' => '/portofoliu'],
        ],
        'en' => [
            'title' => 'Web design Brașov | SiteGo',
            'description' => 'Web design in Brașov for companies and entrepreneurs: fast responsive websites built for search visibility, contact and conversions.',
            'eyebrow' => 'Local service · Brașov',
            'h1' => 'Web design in Brașov for businesses that need a professional website',
            'intro' => 'SiteGo is locally based in Brașov, while remote collaboration is available across Romania and internationally.',
            'service_type' => 'Web design Brașov',
        ],
    ],

    'cat-costa-un-site-2026' => [
        'title' => 'Cât costă un site în 2026? Ghid pentru firme | SiteGo',
        'description' => 'Ghid 2026 despre costul unui site: ce influențează prețul, ce funcționalități contează și cum compari corect ofertele de web design și dezvoltare.',
        'eyebrow' => 'Ghid costuri website',
        'h1' => 'Cât costă un site în 2026 și ce influențează cu adevărat prețul?',
        'intro' => 'Nu există un singur preț corect pentru orice site. Costul depinde de structură, design, conținut, administrare, integrări, limbi, rezervări, plăți și nivelul de dezvoltare personalizată.',
        'service_type' => 'Consultanță website',
        'area_served' => 'România',
        'includes' => [
            'Diferența dintre landing page, site de prezentare și aplicație web',
            'Ce schimbă numărul de pagini și nivelul de personalizare',
            'Când ai nevoie de administrare, rezervări sau plăți',
            'Costuri separate: domeniu, hosting, conținut și integrări',
            'Ce trebuie să verifici într-o ofertă',
            'Cum poți porni simplu și extinde ulterior',
        ],
        'for_who' => 'Pentru antreprenori care compară oferte și vor să înțeleagă ce plătesc, fără să aleagă doar după cel mai mic sau cel mai mare preț.',
        'process' => 'La SiteGo stabilim întâi ce trebuie să facă site-ul și ce conținut are nevoie. Abia apoi putem estima realist complexitatea și oferta.',
        'benefits' => [
            ['title' => 'Compari oferte corect', 'text' => 'Poți verifica dacă două oferte includ aceleași lucruri sau doar folosesc aceleași etichete.'],
            ['title' => 'Eviți funcții inutile', 'text' => 'Nu are sens să plătești pentru funcționalități pe care nu le vei folosi.'],
            ['title' => 'Planifici extinderea', 'text' => 'Poți separa ce este necesar la lansare de ce poate fi adăugat mai târziu.'],
        ],
        'proof' => [
            ['title' => 'Portofoliu SiteGo', 'href' => '/portofoliu', 'text' => 'Compară proiecte reale cu niveluri diferite de complexitate.'],
            ['title' => 'Configurator', 'href' => '/configurator', 'text' => 'Alege funcțiile de care ai nevoie pentru a clarifica proiectul.'],
        ],
        'faqs' => [
            ['question' => 'De ce diferă atât de mult prețurile între furnizori?', 'answer' => 'Pentru că pot fi incluse niveluri foarte diferite de design, conținut, dezvoltare, administrare, SEO, suport și funcționalități.'],
            ['question' => 'Este mai ieftin să pornesc cu un site simplu?', 'answer' => 'De multe ori, da. Dacă funcțiile avansate nu sunt necesare la lansare, pot fi adăugate ulterior.'],
            ['question' => 'Hostingul și domeniul sunt același lucru?', 'answer' => 'Nu. Domeniul este adresa site-ului, iar hostingul este infrastructura pe care rulează site-ul.'],
        ],
        'related' => [
            ['title' => 'Creare site web', 'href' => '/creare-site-web'],
            ['title' => 'Prețuri', 'href' => '/preturi'],
            ['title' => 'Configurator', 'href' => '/configurator'],
        ],
        'en' => [
            'title' => 'How much does a website cost in 2026? | SiteGo',
            'description' => '2026 website cost guide: what changes the price, which features matter and how to compare web design and development offers.',
            'eyebrow' => 'Website cost guide',
            'h1' => 'How much does a website cost in 2026 and what really affects the price?',
            'service_type' => 'Website consultation',
        ],
    ],
];
