<?php

return [
    'template_categories' => [
        ['key' => 'presentation', 'label' => 'Prezentare', 'description' => 'Site-uri pentru firme, cabinete, servicii locale și brand personal.'],
        ['key' => 'sales', 'label' => 'Vânzare', 'description' => 'Landing page-uri pentru oferte, cursuri, campanii și servicii premium.'],
        ['key' => 'booking', 'label' => 'Rezervări', 'description' => 'Site-uri pentru închirieri, cazări, programări și disponibilitate.'],
        ['key' => 'ecommerce', 'label' => 'Magazin online', 'description' => 'Modele pentru produse, cataloage, coș și comenzi.'],
        ['key' => 'custom-platform', 'label' => 'Platforme custom', 'description' => 'Dashboard-uri, conturi, CRM, portaluri și aplicații interne.'],
    ],
    'packages' => [
        ['id' => 1, 'key' => 'start', 'name' => 'Start', 'badge' => 'Simplu', 'label' => 'Pentru început', 'price' => 2500, 'description' => 'Pentru un site simplu, clar, potrivit unei afaceri la început.', 'clientDescription' => 'Site la cheie pornind de la modelul ales.', 'features' => ['Model de site ales', 'Adaptare culori și texte', '4-5 secțiuni principale', 'Formular de contact', 'Variantă mobil și desktop', 'Setări Google de bază']],
        ['id' => 2, 'key' => 'pro', 'name' => 'Pro', 'badge' => 'Recomandat', 'label' => 'Cel mai ales', 'price' => 4500, 'description' => 'Pentru o afacere care vrea un site complet și mai convingător.', 'clientDescription' => 'Site complet, cu mai multe secțiuni și funcționalități.', 'features' => ['Tot ce include Start', 'Mai multe secțiuni personalizate', 'Funcționalități extra', 'Texte structurate mai bine', 'Optimizare viteză', 'Pregătire pentru promovare']],
        ['id' => 3, 'key' => 'premium', 'name' => 'Premium', 'badge' => 'Complet', 'label' => 'Pentru imagine premium', 'price' => 7500, 'description' => 'Pentru proiecte care au nevoie de imagine premium și structură mai avansată.', 'clientDescription' => 'Site mai complex, adaptat serios pe business.', 'features' => ['Tot ce include Pro', 'Design mai personalizat', 'Pagini extra', 'Funcționalități avansate', 'Structură pentru vânzare sau cereri', 'Suport lansare']],
    ],
    'features' => [
        ['id' => 1, 'category' => 'Contact', 'name' => 'Formular de contact', 'plainName' => 'Clientul poate trimite nume, telefon, email și mesaj.', 'price' => 300, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 2, 'category' => 'Contact', 'name' => 'Buton telefon / email', 'plainName' => 'Vizitatorul poate suna sau trimite email rapid.', 'price' => 150, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 3, 'category' => 'Rezervări', 'name' => 'Formular de rezervare', 'plainName' => 'Clientul poate cere o dată, o oră sau o perioadă.', 'price' => 600, 'availableFor' => ['pro', 'premium']],
        ['id' => 4, 'category' => 'Conținut', 'name' => 'Galerie foto / video', 'plainName' => 'Afișezi poze, lucrări, camere, produse sau rezultate.', 'price' => 400, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 5, 'category' => 'Conținut', 'name' => 'Listă servicii și prețuri', 'plainName' => 'Arăți clar ce oferi și cât costă.', 'price' => 350, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 6, 'category' => 'Conținut', 'name' => 'Întrebări frecvente', 'plainName' => 'Răspunzi dinainte la întrebările clientului.', 'price' => 250, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 7, 'category' => 'Încredere', 'name' => 'Testimoniale / recenzii', 'plainName' => 'Afișezi păreri de la clienți sau exemple de rezultate.', 'price' => 350, 'availableFor' => ['pro', 'premium']],
        ['id' => 8, 'category' => 'Localizare', 'name' => 'Google Maps', 'plainName' => 'Clientul vede rapid unde te găsește.', 'price' => 250, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 9, 'category' => 'Vânzare', 'name' => 'Catalog produse', 'plainName' => 'Afișezi produse cu poză, preț și descriere.', 'price' => 900, 'availableFor' => ['pro', 'premium']],
        ['id' => 10, 'category' => 'Administrare', 'name' => 'Panou cereri clienți', 'plainName' => 'Vezi cererile primite într-un admin simplu.', 'price' => 1200, 'availableFor' => ['pro', 'premium']],
        ['id' => 11, 'category' => 'Marketing', 'name' => 'Google Analytics', 'plainName' => 'Vezi câți oameni intră pe site și ce pagini accesează.', 'price' => 300, 'availableFor' => ['start', 'pro', 'premium']],
        ['id' => 12, 'category' => 'Avansat', 'name' => 'Site în română și engleză', 'plainName' => 'Site cu două limbi: română și engleză.', 'price' => 1500, 'availableFor' => ['pro', 'premium']],
    ],
    'templates' => [
        ['id' => 1, 'slug' => 'business-essence', 'categoryKey' => 'presentation', 'category' => 'Prezentare', 'name' => 'Business Essence', 'shortTitle' => 'Site pentru firmă locală', 'description' => 'Pentru firme locale, cabinete, consultanță, servicii premium sau brand personal.', 'basePrice' => 2500, 'buildPriceFrom' => 2500, 'deliveryTime' => '5-7 zile', 'idealFor' => ['Firme locale', 'Cabinete', 'Consultanță'], 'pages' => ['Acasă', 'Despre', 'Servicii', 'Contact']],
        ['id' => 2, 'slug' => 'premium-studio', 'categoryKey' => 'presentation', 'category' => 'Beauty & Salon', 'name' => 'Premium Studio', 'shortTitle' => 'Site pentru studio premium', 'description' => 'Pentru beauty, fotografie, wellness, design interior sau servicii creative.', 'basePrice' => 3500, 'buildPriceFrom' => 3500, 'deliveryTime' => '7-10 zile', 'idealFor' => ['Beauty', 'Fotografie', 'Wellness'], 'pages' => ['Acasă', 'Portofoliu', 'Servicii', 'Contact']],
        ['id' => 3, 'slug' => 'launch-page', 'categoryKey' => 'sales', 'category' => 'Lansare', 'name' => 'Launch Page', 'shortTitle' => 'Landing page', 'description' => 'Pentru promovarea unui produs, serviciu, curs sau ofertă limitată.', 'basePrice' => 2500, 'buildPriceFrom' => 2500, 'deliveryTime' => '5-7 zile', 'idealFor' => ['Campanii', 'Cursuri', 'Servicii'], 'pages' => ['Landing page']],
        ['id' => 4, 'slug' => 'conversion-flow', 'categoryKey' => 'sales', 'category' => 'Campanie', 'name' => 'Conversion Flow', 'shortTitle' => 'Pagină de conversie', 'description' => 'Pagină de vânzare cu beneficii, testimoniale, ofertă și butoane clare.', 'basePrice' => 3500, 'buildPriceFrom' => 3500, 'deliveryTime' => '7-10 zile', 'idealFor' => ['Servicii premium', 'Cursuri', 'Campanii'], 'pages' => ['Landing page extins']],
        ['id' => 5, 'slug' => 'rental-flow', 'categoryKey' => 'booking', 'category' => 'Rezervări', 'name' => 'Rental Flow', 'shortTitle' => 'Site pentru rezervări', 'description' => 'Pentru servicii unde clientul cere disponibilitate, perioadă sau programare.', 'basePrice' => 4500, 'buildPriceFrom' => 4500, 'deliveryTime' => '7-14 zile', 'idealFor' => ['Rezervări', 'Programări', 'Disponibilitate'], 'pages' => ['Acasă', 'Tarife', 'Rezervare', 'Contact']],
        ['id' => 6, 'slug' => 'tourism-stay', 'categoryKey' => 'booking', 'category' => 'Turism', 'name' => 'Tourism Stay', 'shortTitle' => 'Site pentru cazare', 'description' => 'Pentru pensiuni, apartamente, cabane sau experiențe turistice.', 'basePrice' => 4500, 'buildPriceFrom' => 4500, 'deliveryTime' => '7-14 zile', 'idealFor' => ['Cazări', 'Pensiuni', 'Cabane'], 'pages' => ['Acasă', 'Camere', 'Galerie', 'Contact']],
        ['id' => 7, 'slug' => 'simple-shop', 'categoryKey' => 'ecommerce', 'category' => 'Magazin online', 'name' => 'Simple Shop', 'shortTitle' => 'Magazin online simplu', 'description' => 'Pentru afaceri care vor să prezinte produse și să primească cereri sau comenzi.', 'basePrice' => 7500, 'buildPriceFrom' => 7500, 'deliveryTime' => '14-21 zile', 'idealFor' => ['Produse locale', 'Handmade', 'Catalog online'], 'pages' => ['Acasă', 'Produse', 'Categorii', 'Contact']],
        ['id' => 8, 'slug' => 'premium-store', 'categoryKey' => 'ecommerce', 'category' => 'E-commerce', 'name' => 'Premium Store', 'shortTitle' => 'Magazin online premium', 'description' => 'Structură completă pentru produse, variante, coș și checkout.', 'basePrice' => 9500, 'buildPriceFrom' => 9500, 'deliveryTime' => '21+ zile', 'idealFor' => ['Magazine online', 'Branduri', 'Produse premium'], 'pages' => ['Shop', 'Produs', 'Coș', 'Checkout']],
        ['id' => 9, 'slug' => 'client-portal', 'categoryKey' => 'custom-platform', 'category' => 'Platformă custom', 'name' => 'Client Portal', 'shortTitle' => 'Portal client', 'description' => 'Platformă cu autentificare, conturi clienți, dashboard și funcționalități personalizate.', 'basePrice' => 12000, 'buildPriceFrom' => 12000, 'deliveryTime' => '21+ zile', 'idealFor' => ['Dashboard-uri', 'CRM-uri', 'Platforme interne'], 'pages' => ['Login', 'Dashboard', 'Administrare']],
    ],
];
