@extends('pages.layout')
@section('title', __('pages.pricing.title'))
@section('description', __('pages.pricing.description'))
@section('page-title', __('pages.pricing.page_title'))
@section('page-intro', __('pages.pricing.page_intro'))
@section('content')
<section class="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><article class="rounded-[2rem] bg-black p-6 text-white sm:p-8"><p class="text-sm uppercase tracking-[0.25em] text-white/40">{{ __('pages.pricing.hero_eyebrow') }}</p><h2 class="mt-4 text-3xl font-semibold sm:text-4xl">{{ __('pages.pricing.hero_title') }}</h2><p class="mt-4 leading-8 text-white/60">{{ __('pages.pricing.hero_text') }}</p><div class="mt-8 grid gap-4">@foreach(__('pages.pricing.packages') as $package)<div class="rounded-2xl bg-white/10 p-5"><div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><h3 class="text-2xl font-semibold">{{ $package['name'] }}</h3><p class="text-xl font-semibold">{{ $package['price'] }}</p></div><p class="mt-3 leading-7 text-white/60">{{ $package['description'] }}</p><ul class="mt-4 grid gap-2 text-sm text-white/70">@foreach($package['features'] as $feature)<li>✓ {{ $feature }}</li>@endforeach</ul></div>@endforeach</div></article><article class="rounded-[2rem] bg-[#f7f4ef] p-6 sm:p-8"><p class="text-sm uppercase tracking-[0.25em] text-[#8b6f47]">{{ __('pages.pricing.includes_eyebrow') }}</p><h2 class="mt-4 text-3xl font-semibold">{{ __('pages.pricing.includes_title') }}</h2><p class="mt-4 leading-8 text-black/60">{{ __('pages.pricing.includes_text') }}</p><div class="mt-8 grid gap-4">@foreach(__('pages.pricing.includes') as $item)<div class="rounded-2xl bg-white p-5"><h3 class="font-semibold">{{ $item['title'] }}</h3><p class="mt-2 text-sm leading-6 text-black/60">{{ $item['description'] }}</p></div>@endforeach</div></article></section>
<section class="mt-12"><h2 class="text-3xl font-semibold">{{ __('pages.pricing.extras_title') }}</h2><p class="mt-4 max-w-3xl leading-8 text-black/60">{{ __('pages.pricing.extras_text') }}</p><div class="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">@foreach(__('pages.pricing.extras') as $extra)<article class="rounded-2xl bg-white p-5"><div class="flex items-start justify-between gap-4"><h3 class="font-semibold">{{ $extra['name'] }}</h3><strong class="text-right text-[#8b6f47]">{{ $extra['price'] }}</strong></div><p class="mt-3 text-sm leading-6 text-black/60">{{ $extra['description'] }}</p></article>@endforeach</div></section>
<section class="mt-12 rounded-[2rem] bg-black p-6 text-white sm:p-8"><div class="grid gap-6 lg:grid-cols-[1fr_0.6fr] lg:items-center"><div><h2 class="text-3xl font-semibold">{{ __('pages.pricing.cta_title') }}</h2><p class="mt-4 leading-8 text-white/60">{{ __('pages.pricing.cta_text') }}</p></div><div class="flex flex-col gap-3 sm:flex-row lg:flex-col"><a href="/modele-site" class="inline-flex justify-center rounded-full bg-white px-6 py-4 text-sm font-semibold text-black">{{ __('pages.pricing.cta_primary') }}</a><a href="/intrebari-frecvente" class="inline-flex justify-center rounded-full border border-white/20 px-6 py-4 text-sm font-semibold text-white">{{ __('pages.pricing.cta_secondary') }}</a></div></div></section>
@endsection
